django_project/site_proj/site_proj/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("web_app.urls")),
    path("users/", include("users.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

django_project/site_proj/users/urls.py
from django.urls import path
from django.contrib.auth.views import (
    PasswordResetDoneView,
    PasswordResetConfirmView,
    PasswordResetCompleteView,
)
from . import views

app_name = "users"

urlpatterns = [
    path("sign_up/", views.sign_up, name="sign_up"),
    path("login/", views.login_user, name="login"),
    path("logout/", views.logout_user, name="logout"),
    path("profile/<str:user>/", views.profile, name="profile"),
    path("reset-password/", views.ResetPasswordView.as_view(), name="password_reset"),
    path(
        "reset-password/done/",
        PasswordResetDoneView.as_view(template_name="users/password_reset_done.html"),
        name="password_reset_done",
    ),
    path(
        "reset-password/confirm/<uidb64>/<token>/",
        PasswordResetConfirmView.as_view(
            template_name="users/password_reset_confirm.html",
            success_url="/users/reset-password/complete/",
        ),
        name="password_reset_confirm",
    ),
    path(
        "reset-password/complete/",
        PasswordResetCompleteView.as_view(
            template_name="users/password_reset_complete.html"
        ),
        name="password_reset_complete",
    ),
]

django_project/site_proj/web_app/urls.py
from django.urls import path

from . import views

app_name = "web_app"

urlpatterns = [
    path("", views.main, name="main"),
    path("author/<str:name_author>/", views.author, name="author"),
    path("tag/<str:tag_name>/", views.quotes_by_tag, name="quotes_by_tag"),
    path("add_quote/", views.add_quote, name="add_quote"),
]

django_project/site_proj/web_app/models.py
from django.db import models


# Create your models here.
#
class Author(models.Model):
    fullname = models.CharField(max_length=120)
    born_date = models.CharField(max_length=20)
    born_location = models.CharField(max_length=120)
    description = models.CharField()

    def __str__(self):
        return f"{self.fullname}"


class Tag(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        return f"{self.name}"


class Quote(models.Model):
    quote = models.CharField()
    tags = models.ManyToManyField(Tag)
    author = models.ForeignKey(Author, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.quote}"

django_project/site_proj/web_app/forms.py
from django.forms import ModelForm, CharField, TextInput, ModelChoiceField
from .models import Quote, Tag, Author


class TagForm(ModelForm):
    name = CharField(min_length=3, max_length=25, required=True, widget=TextInput())

    class Meta:
        model = Tag
        fields = ["name"]


class QuoteForm(ModelForm):
    quote = CharField(min_length=5, max_length=800, required=True, widget=TextInput())
    # author = ModelChoiceField(queryset=Author.objects.all(), required=False)
    new_author = CharField(
        min_length=10, max_length=150, required=True, widget=TextInput()
    )

    class Meta:
        model = Quote
        fields = ["quote", "new_author"]
        exclude = ["tags"]


class AuthorForm(ModelForm):
    fullname = CharField(
        min_length=3, max_length=120, required=True, widget=TextInput()
    )

    class Meta:
        model = Author
        fields = ["fullname"]

django_project/site_proj/web_app/views.py
from django.shortcuts import render, get_object_or_404, redirect
from web_app.models import Quote, Author, Tag
from django.core.paginator import Paginator
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate
from django.contrib import messages
from .forms import QuoteForm, AuthorForm


def main(request):
    quotes_list = Quote.objects.all().order_by("id")
    paginator = Paginator(quotes_list, 10)  # Show 10 quotes per page.
    page_number = request.GET.get("page", 1)
    quotes = paginator.get_page(page_number)
    quote_slices = [quotes[i : i + 2] for i in range(0, len(quotes), 2)]
    return render(
        request,
        "web_app/index.html",
        {"quote_slices": quote_slices, "page_obj": quotes},
    )


def author(request, name_author):
    author = get_object_or_404(Author, fullname=name_author)
    return render(request, "web_app/author.html", {"author": author})


def quotes_by_tag(request, tag_name):
    tag = Tag.objects.get(name=tag_name)
    quotes = tag.quote_set.all()
    return render(
        request, "web_app/quotes_by_tag.html", {"quotes": quotes, "tag_name": tag_name}
    )


@login_required(login_url="/users/login/")
def add_quote(request):
    tags = Tag.objects.all()

    if request.method == "POST":
        form = QuoteForm(request.POST)
        if form.is_valid():
            # get the author from the form
            author_name = form.cleaned_data["new_author"]
            author = Author.objects.create(fullname=author_name)
            new_quote = form.save(commit=False)
            new_quote.author = author
            new_quote.quote = f"“{new_quote.quote}”"
            new_quote.save()

            choice_tags = Tag.objects.filter(name__in=request.POST.getlist("tags"))
            for tag in choice_tags.iterator():
                new_quote.tags.add(tag)

            return redirect(to="web_app:main")
        else:
            return render(
                request, "web_app/add_quote.html", {"tags": tags, "form": form}
            )

    return render(
        request, "web_app/add_quote.html", {"tags": tags, "form": QuoteForm()}
    )

django_project/site_proj/web_app/templates/web_app/add_quote.html
{% extends "web_app/base.html" %}

{% block content %}

<div class="form-container">
    <form method="POST" action="{% url 'web_app:add_quote' %}" class="form">
        {% csrf_token %}
        <div style="padding: 10px;">
            <div class="row" style="display: flex; justify-content: space-between;">
                <div style="flex: 1; color:white;">
                    <label for="{{ form.new_author.id_for_label }}">Author name:</label>
                    <textarea rows="1" id="{{ form.new_author.id_for_label }}" name="{{ form.new_author.name}}"
                    style="resize: none; width: 100%; background-color: transparent; color: white;  border-radius: 5px;"></textarea>
                </div>
                <div style="flex: 1; color:white;">
                    <label for="Tags">Tags:</label>
                    <select name="tags" style="width: 100%; background-color: transparent; color: white;  border-radius: 5px;">
                        {% for tag in tags %}
                        <option value="{{tag.name}}">{{tag.name}}</option>
                        {% endfor %}
                    </select>
                </div>
            </div>
        </div>
        <span>{{ form.errors.new_author }}</span>

        <div style="padding: 10px; color:white;">
            <label for="{{ form.quote.id_for_label }}">Quote:</label>
            <textarea id="{{ form.quote.id_for_label }}" name="{{ form.quote.name }}" rows="8"
                style="resize: none; width: 100%; background-color: transparent; color: white;  border-radius: 5px;"></textarea>
        </div>
        <span>{{ form.errors.quote }}</span>

        <div class="grid">
            <button type="submit" class="btn btn-primary">Submit</button>
            <button type="reset" class="btn btn-primary">Reset</button>
        </div>
    </form>
</div>

{% endblock %}

django_project/site_proj/web_app/templates/web_app/author.html
{% extends "web_app/base.html" %}

{% block content %}
<h1>
    <div class="container text-center" style="font-size: 80%; padding-bottom: 30px; color: white;">
        {{author.fullname}}
    </div>
</h1>
<div class="col col-lg-12 mb-4 mb-lg-0" style="color: white;">
    <figure class="p-3 rounded" style="border-left: .25rem solid #a34e78;">
        <blockquote class="blockquote pb-2" style="font-size: 100%;">
            <p>
                <b>Born:</b> {{author.born_date}}, {{author.born_location}}
            </p>
        </blockquote>
        <blockquote class="blockquote pb-2" style="font-size: 90%;"></blockquote>
        <p>
            <b>Description:</b> {{author.description}}
        </p>
        </blockquote>
    </figure>
{% endblock %}

django_project/site_proj/web_app/templates/web_app/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8" />
    <title>
        quotes.com
    </title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous" />
    <link rel="stylesheet" href="{% static 'web_app/style.css' %}">
    <link rel="icon" href="{% static 'web_app/img.png' %}">
</head>

<body>
    <header>
        {% include "web_app/navbar.html" %}
    </header>
    <main class="container" style="padding-top: 100px;">
        {% block content %}
        {% endblock %}
    </main>
    <footer class="text-center text-white py-3">
        &copy; 2023 Made by Wargoth
    </footer>
</body>

</html>

django_project/site_proj/web_app/templates/web_app/index.html
{% extends "web_app/base.html" %}

{% block content %}
<h1>
    <div class="container text-center" style="font-size: 80%; padding-bottom: 40px; color: white">
        Hello! Welcome to quotes.com
    </div>
</h1>
<div class="container py-1">
    {% for quote_slice in quote_slices %}
    <div class="row d-flex flex-column align-items-start flex-lg-row">
        {% for quote in quote_slice %}
        <div class="col col-lg-6 mb-4 mb-lg-0">
            <figure class="p-3 rounded" style="border-left: .25rem solid #a34e78; color: white; word-wrap: break-word;">
                <blockquote class="blockquote pb-2" style="font-size: 90%;">
                    <p>
                        {{ quote.quote }}
                    </p>
                </blockquote>
                <figcaption class="blockquote-footer font-italic" style="color: white; word-wrap: break-word;">
                    Author: 
                <a style="color: aqua;" href="{% url 'web_app:author' quote.author.fullname %}">
                    {{ quote.author.fullname }}
                </a>
                </figcaption>
                <figcaption class="blockquote-footer font-italic" style="color: white;">
                    Tags: {% for tag in quote.tags.all %}
                <a style="color:tomato ;" href="{% url 'web_app:quotes_by_tag' tag.name %}">
                    {{ tag.name }}
                </a>
                {% if not forloop.last %}, {% endif %}{% endfor %}
                </figcaption>
            </figure>
        </div>
        {% endfor %}
    </div>
    {% endfor %}
</div>
{% include "web_app/pagination.html" %}
{% endblock %}

django_project/site_proj/web_app/templates/web_app/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
    <div class="container-fluid">
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="/">
                        Home
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'users:sign_up' %}">
                        Sign up
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'users:login' %}">
                        Login
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'web_app:add_quote' %}">
                        Add quote
                    </a>
                </li>
                {% if user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'users:profile' user.username %}">
                        Profile
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'users:logout' %}">
                        Logout
                    </a>
                </li>
                <li class="navbar-text ml-auto">
                    You have been logged in, <b>{{ user.username }}!</b>
                </li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>

django_project/site_proj/web_app/templates/web_app/pagination.html
<nav aria-label="Page navigation" class="d-flex justify-content-center">
    <ul class="pagination py-4">
        {% if page_obj.has_previous %}
            <li class="page-item">
                <a class="page-link" href="?page={{ page_obj.previous_page_number }}" style="background-color: transparent;  color: aqua;">
                    Previous
                </a>
            </li>
        {% else %}
            <li class="page-item disabled">
                <span class="page-link" style="background-color: transparent;  color: aqua;">
                    Previous
                </span>
            </li>
        {% endif %}
        {% for i in page_obj.paginator.page_range %}
            {% if page_obj.number == i %}
                <li class="page-item active">
                    <a class="page-link" href="#">
                        {{ i }}
                    </a>
                </li>
            {% else %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ i }}" style="background-color: transparent;  color: aqua;">
                        {{ i }}
                    </a>
                </li>
            {% endif %}
        {% endfor %}
        {% if page_obj.has_next %}
            <li class="page-item">
                <a class="page-link" href="?page={{ page_obj.next_page_number }}" style="background-color: transparent;  color: aqua;">
                    Next
                </a>
            </li>
        {% else %}
            <li class="page-item disabled">
                <span class="page-link" style="background-color: transparent;  color: aqua;">
                    Next
                </span>
            </li>
        {% endif %}
    </ul>
</nav>

django_project/site_proj/web_app/templates/web_app/quote_add.html
{% extends "web_app/base.html" %}

{% block content %}

{% if messages %}
<ul class="messages py-5 h-50">
    {% for message in messages %}
    <li{% if message.tags %} class="{{ message.tags }}" {% endif %}>{{ message }}</li>
        {% endfor %}
</ul>
{% endif %}

<form method="post" action="{% url 'web_app:add_quote' %}">
    {% csrf_token %}
    <div class="form-outline mb-4">
        <input type="author" id="form4Example2" class="form-control" />
        <label class="form-label">{{ form.new_author.label }}</label>
        <span>{{ form.errors.new_author }}</span>
    </div>

    <!-- Message input -->
    <div class="form-outline mb-4">
        <textarea class="form-control" id="form4Example3" rows="4"></textarea>
        <label class="form-label">{{ form.quote.label }}</label>
        <span>{{ form.errors.quote }}</span>
    </div>

    <!-- Checkbox -->
    <div class="form-outline mb-4" style="padding: 20px; width: 100%;">
        <label for="Tags">Tags:</label>
        <select name="tags">
            {% for tag in tags %}
            <option value="{{tag.name}}">{{tag.name}}</option>
            {% endfor %}
        </select>
        <span>{{ quote_form.errors.tags }}</span>
    </div>

    <!-- Submit button -->
    <button type="submit" class="btn btn-primary btn-block mb-4">Publish</button>
    {% endblock %}
</form>

django_project/site_proj/web_app/templates/web_app/quotes_by_tag.html
{% extends "web_app/base.html" %}

{% block content %}

<div class="container text-left" style="font-size: 70%; color: white;">
    <h1>
        Tag: {{ tag_name }}
    </h1>
</div>
<div class="row d-flex flex-column align-items-start flex-lg-row">
    {% for quote in quotes %}
    <div class="col col-lg-6 mb-4 mb-lg-0" style="color: white;">
        <figure class="p-3 rounded" style="border-left: .25rem solid #a34e78;">
            <blockquote class="blockquote pb-2" style="font-size: 90%;">
                <p>
                    {{ quote.quote }}
                </p>
            </blockquote>
            <figcaption class="blockquote-footer font-italic" style="color: white;">
                Author: 
                <a style="color: aqua;" href="{% url 'web_app:author' quote.author.fullname %}">
                    {{ quote.author.fullname }}
                </a>
            </figcaption>
            <figcaption class="blockquote-footer font-italic" style="color: white;">
                Tags: {% for tag in quote.tags.all %}
                <a style="color:tomato ;" href="{% url 'web_app:quotes_by_tag' tag.name %}">
                    {{ tag.name }}
                </a>{% if not forloop.last %}, {% endif %}{% endfor %}
            </figcaption>
        </figure>
    </div>
    {% endfor %}
</div>
{% endblock %}