django_project/site_proj/site_proj/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("web_app.urls")),
    path("users/", include("users.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

django_project/site_proj/users/urls.py
from django.urls import path
from django.contrib.auth.views import (
    PasswordResetDoneView,
    PasswordResetConfirmView,
    PasswordResetCompleteView,
)
from . import views

app_name = "users"

urlpatterns = [
    path("sign_up/", views.sign_up, name="sign_up"),
    path("login/", views.login_user, name="login"),
    path("logout/", views.logout_user, name="logout"),
    path("profile/<str:user>/", views.profile, name="profile"),
    path("reset-password/", views.ResetPasswordView.as_view(), name="password_reset"),
    path(
        "reset-password/done/",
        PasswordResetDoneView.as_view(template_name="users/password_reset_done.html"),
        name="password_reset_done",
    ),
    path(
        "reset-password/confirm/<uidb64>/<token>/",
        PasswordResetConfirmView.as_view(
            template_name="users/password_reset_confirm.html",
            success_url="/users/reset-password/complete/",
        ),
        name="password_reset_confirm",
    ),
    path(
        "reset-password/complete/",
        PasswordResetCompleteView.as_view(
            template_name="users/password_reset_complete.html"
        ),
        name="password_reset_complete",
    ),
]

django_project/site_proj/users/models.py
from django.db import models
from django.contrib.auth.models import User
from PIL import Image


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    avatar = models.ImageField(default="logo.png", upload_to="profile_images")

    def __str__(self):
        return self.user.username

    # resizing images
    def save(self, *args, **kwargs):
        super().save()

        img = Image.open(self.avatar.path)

        if img.height > 250 or img.width > 250:
            new_img = (250, 250)
            img.thumbnail(new_img)
            img.save(self.avatar.path)

django_project/site_proj/users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User
from .models import Profile


class RegisterForm(UserCreationForm):
    username = forms.CharField(
        max_length=100,
        required=True,
        widget=forms.TextInput(
            attrs={
                "class": "input-group",
                "style": "background-color: transparent; color: white;  border-radius: 5px;",
                "placeholder": "Enter your username",
            }
        ),
    )

    email = forms.EmailField(
        max_length=150,
        required=True,
        widget=forms.TextInput(
            attrs={
                "class": "input-group",
                "style": "background-color: transparent; color: white;  border-radius: 5px;",
                "placeholder": "Enter your email",
            }
        ),
    )

    password1 = forms.CharField(
        max_length=50,
        required=True,
        widget=forms.TextInput(
            attrs={
                "class": "input-group",
                "type": "password",
                "style": "background-color: transparent; color: white;  border-radius: 5px;",
                "placeholder": "Enter your password",
            }
        ),
    )
    password2 = forms.CharField(
        max_length=50,
        required=True,
        widget=forms.TextInput(
            attrs={
                "class": "input-group",
                "type": "password",
                "style": "background-color: transparent; color: white;  border-radius: 5px;",
                "placeholder": "Confirm your password",
            }
        ),
    )

    class Meta:
        model = User
        fields = ["username", "email", "password1", "password2"]

    def clean_username(self):
        """
        Returns the name if entered name is unique otherwise gives duplicate name error.
        """
        username = self.cleaned_data["username"]
        if User.objects.filter(username=username).exists():
            raise forms.ValidationError("This username is already taken.")
        return username

    def clean_email(self):
        """
        Returns the email if entered email is unique otherwise gives duplicate_email error.
        """
        email = self.cleaned_data["email"]
        if User.objects.filter(email=email).exists():
            raise forms.ValidationError("Duplicate email error")
        return email


class LoginForm(AuthenticationForm):
    username = forms.CharField(
        max_length=100,
        required=True,
        widget=forms.TextInput(
            attrs={
                "class": "input-group",
                "style": "background-color: transparent; color: white;  border-radius: 5px;",
                "placeholder": "Enter your username",
            }
        ),
    )
    password = forms.CharField(
        max_length=50,
        required=True,
        widget=forms.TextInput(
            attrs={
                "class": "input-group",
                "type": "password",
                "style": "background-color: transparent; color: white;  border-radius: 5px;",
                "placeholder": "Enter your password",
            }
        ),
    )

    class Meta:
        model = User
        fields = ["username", "email", "password"]


class ProfileForm(forms.ModelForm):
    username = forms.CharField(required=True)
    email = forms.EmailField(required=False)
    avatar = forms.ImageField(widget=forms.FileInput())

    class Meta:
        model = Profile
        fields = ["username", "email", "avatar"]

    def clean_username(self):
        """
        Returns the name if entered name is unique otherwise gives duplicate name error.
        """
        username = self.cleaned_data["username"]
        if (
            User.objects.filter(username=username).exists()
            and username != self.instance.user.username
        ):
            raise forms.ValidationError("This username is already taken.")
        return username

    def clean_email(self):
        """
        Returns the email if entered email is unique otherwise gives duplicate_email error.
        """
        email = self.cleaned_data["email"]
        if (
            User.objects.filter(email=email).exists()
            and email != self.instance.user.email
        ):
            raise forms.ValidationError("Duplicate email error")
        return email

django_project/site_proj/users/views.py
from django.contrib import messages
from django.shortcuts import render, redirect

from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.views import PasswordResetView
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse_lazy

from .forms import RegisterForm, LoginForm, ProfileForm
from .models import Profile


def sign_up(request):
    if request.user.is_authenticated:
        return redirect(to="web_app:main")

    if request.method == "POST":
        form = RegisterForm(request.POST)
        if form.is_valid():
            form.save()
            user = form.cleaned_data.get("username")
            messages.success(request, f"Account successfully created for {user}")
            return redirect(to="users:login")

        print("Form is not valid")
        return render(request, "users/sign_up.html", context={"form": form})

    return render(request, "users/sign_up.html", context={"form": RegisterForm()})


def login_user(request):
    if request.user.is_authenticated:
        return redirect(to="web_app:main")

    if request.method == "POST":
        user = authenticate(
            username=request.POST["username"], password=request.POST["password"]
        )
        if user is None:
            messages.error(request, "Username or password didn't match")
            return redirect(to="users:login")

        login(request, user)
        return redirect(to="web_app:main")

    return render(request, "users/login.html", context={"form": LoginForm()})


@login_required
def logout_user(request):
    logout(request)
    return redirect(to="web_app:main")


@login_required
def profile(request, user):
    Profile.objects.get_or_create(user=request.user)
    if request.method == "POST":
        profile_form = ProfileForm(
            request.POST, request.FILES, instance=request.user.profile
        )
        if profile_form.is_valid():
            profile_form.save()
            request.user.username = request.POST["username"]
            request.user.email = request.POST["email"]
            request.user.save()
            messages.success(request, "Your profile is updated successfully")
            return redirect(to="users:profile", user=request.user)
        messages.error(request, "Error update profile!")

    profile_form = ProfileForm(instance=request.user.profile)
    return render(request, "users/profile.html", {"profile_form": profile_form})


class ResetPasswordView(SuccessMessageMixin, PasswordResetView):
    template_name = "users/password_reset.html"
    email_template_name = "users/password_reset_email.html"
    html_email_template_name = "users/password_reset_email.html"
    success_url = reverse_lazy("users:password_reset_done")
    success_message = (
        "An email with instructions to reset your password has been sent to %(email)s."
    )
    subject_template_name = "users/password_reset_subject.txt"

django_project/site_proj/users/templates/users/login.html
{% extends "web_app/base.html" %}

{% block content %}
{% load static %}

<link rel="stylesheet" href="{% static 'users/style.css' %}">

{% if messages %}
<ul class="messages text-center">
    {% for message in messages %}
    <li{% if message.tags %} class="{{ message.tags }}" {% endif %}>{{ message }}</li>
        {% endfor %}
</ul>
{% endif %}

<div class="form-container">
    <h2 style="font-size: 150%;">
        Login
    </h2>

    <form method="post" action="{% url 'users:login' %}" class="form">
        {% csrf_token %}
        <div class="input-group">
            <label for="username">Username:</label>
            {{ form.username }}
            <span>{{ form.errors.username }}</span>
        </div>
        <br>
        <div class="input-group">
            <label for="password">Password:</label>
            {{ form.password }}
            <span>{{ form.errors.password }}</span>
        </div>
        <p class="small"><a class="text-primary" href="{% url 'users:password_reset' %}">Forgot password?</a></p>
        <div class="grid">
            <button type="submit" class="btn btn-primary">Submit</button>
            <p class="mb-0  text-center">Don't have an account?
                <a href="{% url 'users:sign_up' %}" class="text-primary fw-bold">
                    Sign Up
                </a>
            </p>
        </div>
    </form>
</div>

{% endblock %}

django_project/site_proj/users/templates/users/logout.html
{% extends "main/header.html" %}
{% block content %}
    <h2>You have been logged out</h2>
    <div class="border-bottom pt-3"  style="min-height:65vh;">
        <small class="text-muted">
            <a href="{% url 'users:login' %}">Log In Again</a>
        </small>
    </div>
{% endblock content %}

django_project/site_proj/users/templates/users/password_reset.html
{% extends "web_app/base.html" %}

{% block content %}

{% load static %}
<link rel="stylesheet" href="{% static 'users/style.css' %}">

<div class="form-container">
    <h2>
        Password reset
    </h2>
    <form method="post" class="input">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary">
            Request password reset
        </button>
    </form>
</div>
{% endblock %}

django_project/site_proj/users/templates/users/password_reset_complete.html
{% extends "web_app/base.html" %}

{% block content %}
{% load static %}
<link rel="stylesheet" href="{% static 'users/style.css' %}">

<div class="form-container">
    <h2>
        Password reset complete!
    </h2>
</div>
{% endblock %}

django_project/site_proj/users/templates/users/password_reset_confirm.html
{% extends "web_app/base.html" %}

{% block content %}

{% load static %}
<link rel="stylesheet" href="{% static 'users/style.css' %}">

<style>
    .form-container {
        position: relative;
        top: -20px;
    }
</style>

<div class="form-container">
    <h2 style="text-align: center; font-size: 100%;">
        Enter new password
    </h2>
    <form method="post" style="text-align: center; font-size: 85%;" class="input">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary" style="text-align: center; font-size: 95%">
            Save new password
        </button>
    </form>
</div>
{% endblock %}

django_project/site_proj/users/templates/users/password_reset_done.html
{% extends "web_app/base.html" %}

{% block content %}

{% load static %}
<link rel="stylesheet" href="{% static 'users/style.css' %}">

<div class="form-container">
    <h2>
        Password reset request sent
    </h2>
    <p>
        We've emailed you with instructions on how to reset your password.
    </p>
</div>
{% endblock %}

django_project/site_proj/users/templates/users/password_reset_email.html
{% autoescape off %}
{% load static %}
<link rel="stylesheet" href="{% static 'users/style.css' %}">

<div class="form-container">
    <body>
        <p>
            Hi {{ user.username }},
        </p>
        <p>
            You requested a password reset for your account. Please follow this link to set a new password:
        </p>
        <p>
            <a href="{{ protocol }}://{{ domain }}{% url 'users:password_reset_confirm' uidb64=uid token=token %}">
                {{ protocol }}://{{ domain }}{% url 'users:password_reset_confirm' uidb64=uid token=token %}
            </a>
        </p>
        <p>
            If you didn't request a password reset, please ignore this email.
        </p>
        <p>
            Thanks,
        </p>
        <p>
            The Our Team
        </p>
    </body>
</div>
{% endautoescape %}

django_project/site_proj/users/templates/users/profile.html
{% extends "web_app/base.html" %}

{% block content %}
{% load static %}

<link rel="stylesheet" href="{% static 'users/style.css' %}">

{% if messages %}
<div style="text-align: center;">
    {% for message in messages %}
    <div {% if message.tags %} class="alert-{{ message.tags }}" {% endif %}>
        {{ message }}
    </div>
    {% endfor %}
</div>
{% endif %}

<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="container rounded mt-3" style="color: white;">
        <div class="row">
            <div class="col-md-3 border-right">
                <div class="d-flex flex-column align-items-center text-center p-3 py-1">
                    <img class="rounded-circle mt-5" width="152px" src="{{ user.profile.avatar.url }}"
                        alt="Avatar of user" />
                    <span class="font-weight-bold">
                        {{user.username}}
                    </span>
                    <span class="text-white">
                        {{user.email}}
                    </span>
                </div>
                <div class="mt-3 text-center">
                    <label for="avatar" class="btn btn-primary avatar-button">
                        Choose Avatar
                    </label>
                    <input type="file" id="avatar" name="avatar" style="display: none;">
                </div>
            </div>
            <div class="col-md-5 border-right">
                <div class="p-3 py-1">
                    <div class="d-flex justify-content-between align-items-center mb-3">
                        <h4 style="text-align: center;">
                            Profile Settings
                        </h4>
                    </div>
                    <div class="row mt-3">
                        <div class="col-md-12">
                            <label for="username" class="labels">Change name</label>
                            <input type="text" placeholder="Username" name="username" value="" class="form-control">
                        </div>
                    </div>
                    <div class="row mt-3">
                        <div class="col-md-12">
                            <label for="email" class="labels">Change mail</label>
                            <input type="text" placeholder="Email" name="email" value="" class="form-control">
                        </div>
                    </div>
                    <div class="mt-5 text-center">
                        <button class="btn btn-primary profile-button" type="submit">
                            Save Profile
                        </button>
                        <button class="btn btn-secondary profile-button" type="reset">
                            Reset Profile
                        </button>
                    </div>
                    <div class="row mt-3 justify-content-center">
                        <button class="btn btn-primary profile-button" style="width: 70%;">
                            <a href="{% url 'users:password_reset' %}" style="color: white; text-decoration: none;">
                                Reset Password
                            </a>
                        </button>
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>

{% endblock content %}

django_project/site_proj/users/templates/users/sign_up.html
{% extends "web_app/base.html" %}

{% block content %}
{% load static %}

<link rel="stylesheet" href="{% static 'users/style.css' %}">

<div class="form-container">
    {% if messages %}
    <ul class="messages" style="text-align: center; font-size: small;">
        {% for message in messages %}
        <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
        {% endfor %}
    </ul>
    {% endif %}
    <h2 style="font-size: 110%; padding-bottom: 20px">
        Sign Up
    </h2>
    
    <form method="post" action="{% url 'users:sign_up' %}" style="font-size: 85%;">
        {% csrf_token %}
        <div class="input-group grid-container" style="width: 100%;">
            <label for="username">Username:</label>
                {{ form.username }}
            <span>{{ form.errors.username }}</span>
        </div>
        <div class="input-group grid-container" style="width: 100%;">
            <label for="email">Email:</label>
                {{ form.email }}
            <span>{{ form.errors.email }}</span>
        </div>
        <div class="input-group grid-container" style="width: 100%;">
            <label for="password1">Password:</label>
                {{ form.password1 }}
            <span>{{ form.errors.password1 }}</span>
        </div>
        <div class="input-group grid-container" style="width: 100%;">
            <label for="password2">Password confirmation:</label>
            {{ form.password2 }}
            <span>{{ form.errors.password2 }}</span>
        </div>
        <div class="grid">
            <button type="submit" class="btn btn-primary">Submit</button>
            <button type="reset" class="btn btn-primary">Reset</button>
        </div>
    </form>
</div>

{% endblock %}